In [50]:
import numpy as np

In [51]:
#Exercise 1: Create a 4X2 integer array and Print its attributes.

array = np.zeros((4,2), dtype=np.int64)
print("Array shape is: " + str(array.shape))
print("Array dimensions are: " + str(array.ndim))
print("Length of each element is array is: " + str(array.itemsize))


Array shape is: (4, 2)
Array dimensions are: 2
Length of each element is array is: 8


In [52]:
#Exercise 2: Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10.

array = np.arange(100, 200, 10).reshape(5,2)
print(array)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [53]:
#Exercise 3: Following is the provided numpy array. return array of items in the second column from all rows.

sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]], dtype=np.int64)
array = np.array([sampleArray[0, 1], sampleArray[1, 1], sampleArray[2,1]])
print("Printing Input Array" + "\n" + str(sampleArray))
print("Printing array of items in the second column from all rows" + "\n" + str(array))


Printing Input Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]
Printing array of items in the second column from all rows
[22 55 88]


In [54]:
#Exercise 4: Following is the given numpy array return array of odd rows and even columns.
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24],[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
outputArray = sampleArray[0: 5: 2, 1: 4: 2]
print("Printing Input Array" + "\n" + str(sampleArray) + "\n")
print("Printing Output Array" + "\n" + str(outputArray))

Printing Input Array
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

Printing Output Array
[[ 6 12]
 [30 36]
 [54 60]]


In [55]:
#Exercise 5: Add the following two NumPy arrays.
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
output = arrayOne + arrayTwo

print("addition of two arrays is" + "\n" + str(output))


addition of two arrays is
[[20 39 33]
 [25 25 28]]
